### ISSUE TITLE
Can I share my WSPAM scripts and AutoBuild templates?

### ISSUE THREAD

**Issue by ghost** [Wurst-Imperium/WurstClient.net#1]
I want to share scripts with others. They will share it too. Please add an upload button

**Comment by Alexander01998** [comment]
You can submit your WSPAM scripts and AutoBuild templates by opening an Issue with the file(s) attached.

**Comment by Alexander01998** [comment]
Remember to wrap them in three backticks <code>```</code> so that they render nicely.
