### ISSUE TITLE
Collection for redirects

### ISSUE THREAD

**Issue by Alexander01998** [Wurst-Imperium/WurstClient.net#100]
```
_redirects/
  ideas.html
  bugs.html
  changelog.html
```

Having all the redirects in one place removes a lot of clutter.

**Comment by ghost** [comment]
Alexander, OP-sign is deleted but, the wiki page isn't deleted. (Or there isn't a "this is removed in ..." warning in that page.)

**Comment by Alexander01998** [comment]
> Alexander, OP-sign is deleted but, the wiki page isn't deleted. (Or there isn't a "this is removed in ..." warning in that page.)

The OP-Sign page is missing a history section, that's why.
