### ISSUE TITLE
Contributor List (a.k.a Wall of Fame)

### ISSUE THREAD

**Issue by Alexander01998** [Wurst-Imperium/WurstClient.net#101]
`wurst-client.tk/contributors`
=> list of contributors

`wurst-client.tk/contributors/<contributor_name>`
=> list of contributions with links, e.g.

> - Made the [Session Stealer](https://www.wurst-client.tk/wiki/Special_Features/Force_OP_%28Session_Stealer%29/) in [Wurst 2.3](https://www.wurst-client.tk/news/2015-08-21-Wurst-2.3-released/).

**Comment by Dinosaurismus** [comment]
This could be like the projects list on your website with a grid of contributors (wurst-client.tk/contributors) and when you click on a button in one of the boxes then it comes to the detailed info (wurst-client.tk/contributors/<contributor_name>)
