### ISSUE TITLE
"Report A Bug" button in Wurst Update posts

### ISSUE THREAD

**Issue by Alexander01998** [Wurst-Imperium/WurstClient.net#104]

**Comment by kjwsc8910** [comment]
Im not sure if i am in the right place to report a bug. but there are 2 game breaking bug that effect singleplayer and multiplayer bug 1 is client side you are in a place server side everyone is beating you up from somewere else and you cant hit them. :( and bug number 2 is that you are never aiming correct even with bow aimbot you could aim strait fowerd but if you dropsomething use a bow or throw snowballs it will go some were else. :( .

**Comment by mcccs** [comment]
1) I don't understand what you mean.
2) Do you know how difficult is predicting movement? You'll need a supercomputer to predict the exact movement. And Wurst has linear movement predictions, at least.

3) Visit [www.wurst-client.tk/bugs](https://wurst-client.tk/bugs) to report bugs.

**Comment by kjwsc8910** [comment]
I don't know what to name them but the first one is like blink if activated but it's not and they are hurting me and can see me in different places and I can always hurt them. Second bug is were I look one way but it thinks I'm looking somewhere else so I shoot arrows where I'm not looking. I don't know what to call them. 


From KJ's iPhone 6

**Comment by mcccs** [comment]
1) Mineplex has an invisibility bug, and it can't be solved by us.
1A) Or that player may be invisible, I suggest you to enable TrueSight (But it is not implemented on Wurst v3.0pre1 and newer *yet*.)
2) The new KillAura broke it, and I can confirm this bug. 👍

**Comment by kjwsc8910** [comment]
It wasn't on mineplex and it was were I was in a different play to were I was and I tried the panic button to see if it was a hack messing it up. 


From KJ's iPhone 6

**Comment by mcccs** [comment]
Or that player may be using invisibility hack?

**Comment by kjwsc8910** [comment]
I mean I'm being attacked by people but there attacking somewhere I just was it happens all the time



From KJ's iPhone 6

**Comment by mcccs** [comment]
I don't think this it is caused by Wurst, a server glitch maybe?

**Comment by kjwsc8910** [comment]
That's what I thought at first but I tested it on single player yesterday and it was doing the second glich White where I was facing but I went to try it again and wurst updated the aim glich isn't happening yet going to try the first glich. 


From KJ's iPhone 6

**Comment by kjwsc8910** [comment]
The bow glich started again. 


From KJ's iPhone 6

**Comment by mcccs** [comment]
OK, then open a bug report in [www.wurst-client.tk/bugs/](http://www.wurst-client.tk/bugs/).

**Comment by kjwsc8910** [comment]
What should I call them


From KJ's iPhone 6

**Comment by mcccs** [comment]
Killaura and the bow bug maybe?

**Comment by mcccs** [comment]
But don’t forget to send them in seperate issues.
