### ISSUE TITLE
Not working on Spigot 1.9.4

### ISSUE THREAD

**Issue by D3rkcrafter** [Wurst-Imperium/WurstClient.net#109]
Wurst v3.2 doesn't work on Spigot 1.9.4. Is there a possible way to fix this so i can use it on my favorite server?

**Comment by ghost** [comment]
Wrong repository and 

## Duplicate: https://github.com/Wurst-Imperium/Wurst-Client-Bugs/issues/27

![dupli](https://cloud.githubusercontent.com/assets/11584045/15435554/a30d6456-1ec5-11e6-83d3-787a691381ea.PNG)
