### ISSUE TITLE
TrueSight not working

### ISSUE THREAD

**Issue by script-head** [Wurst-Imperium/WurstClient.net#111]
Currently, true sight is not showing invisible entities
[http://i.imgur.com/hAIna6p.png](http://i.imgur.com/hAIna6p.png)

**Comment by mcccs** [comment]
## Duplicate: https://github.com/Wurst-Imperium/Wurst-Client-Bugs/issues/34

[](https://cloud.githubusercontent.com/assets/11584045/15435554/a30d6456-1ec5-11e6-83d3-787a691381ea.PNG)
