### ISSUE TITLE
Source not found

### ISSUE THREAD

**Issue by Joshua1999** [Wurst-Imperium/WurstClient.net#115]
I have attempted to compile Wurst 3.4 on Windows 10 following the contribution instructions, substituting MCP 9.10 with MCP 9.24 beta 1 and MC 1.8 with MC 1.9.

When I click on debug like you do in your "fixing wurst bugs" video on youtube, I seem to get a source not found error.

This is the error:

> The JAR file C:************************\lwjgl-2.9.4-nightly-20150209.jar has no source attachment. You can attach the source by clicking Attach Source below:

In my debug configuration I have the main class set to "net.minecraft.client.main.Main" and I am running it from the wurst project. I did not add anything else (no arguements, JRE, Classpath, etc.)

I wanted to know if any of you know where I can find this "source". I have been googleing around for the past 2-3 hours, and here is what I have tried.

Linking to the dll files in native downloaded from lwjgl.org for LWJGL 2.9.4

Linking to all of the other folders in that same file.

If anyone could help, that would be amazing. Thank you :)

**Comment by ghost** [comment]
Download lwjgl 2.9.2 and import native/windows as source.

Also: Wrong repository.

**Comment by Joshua1999** [comment]
I have followed @mcccs instructions but I have ran into another error regarding Sys.class.

Am I missing something?

![help](https://cloud.githubusercontent.com/assets/19869617/15987417/726fc2b2-2fdc-11e6-9be4-a8c7cd936f65.png)

Also, I am sorry that this is the wrong repo. The client repo had issues disabled so I came to the next best thing.

**Comment by ghost** [comment]
Revert it and do this:
![screen shot 2016-06-12 at 11 07 51](https://cloud.githubusercontent.com/assets/11584045/15989920/98e9f61c-308e-11e6-9e1f-f4905a1d9bf9.png)

Find _LWJGL.jar_ on the list and click the _native library location_.
![](http://wiki.lwjgl.org/images/3/34/Eclipse5.png)

Then select the folder which includes natives for your OS.
