### ISSUE TITLE
FAQ / Q&A section

### ISSUE THREAD

**Issue by Alexander01998** [Wurst-Imperium/WurstClient.net#116]
![image](https://cloud.githubusercontent.com/assets/10100202/16049425/f8e86ba0-3257-11e6-92d9-1927afe9693c.png)

**Comment by AlemGames** [comment]
Alexander im having truble with mz 1.8 Alt Manager so theres this website mcleaks.net 10 free minecraft premium accounts but some not working ofc and i tried over 15 accounts the first 5 says Wrong password and then it says cannot contact with authentication server help plz

**Comment by mcccs** [comment]
MCLeaks accounts are deleted by Mojang.
