### ISSUE TITLE
How to Compile Wurst 3.X?

### ISSUE THREAD

**Issue by Joshua1999** [Wurst-Imperium/WurstClient.net#118]
I have made many edits to my copy of Wurst and I would like to compile them to be used via the minecraft launcher (not Eclipses built in debug mode).

If @Alexander01998 could please share his build settings, that would be marvelous. If it works, I will gladly write an update to the contributing guide on the website using my newfound knowledge.

Thank You :) 

(Also for next time, could someone please tell me the correct repo to open an issue in? Wurst does not have an issue tracker and the "Wurst-Bugs" repo says to only post in there if it is a bug. Thanks :D)

**Comment by ghost** [comment]
Currently we don't have Question-Answer repo, but you can send an E-Mail to [contact.wurstimperium@gmail.com](mailto:contact.wurstimperium@gmail.com?subject=How to Compile Wurst 3.X&body=Alexander I need help. Could you please tell me how to Compile Wurst 3.X?)

Also, you should wait for 4.0, @Alexander01998 started to work on it.
