### ISSUE TITLE
Wurst alt manager bug

### ISSUE THREAD

**Issue by DevMaxC** [Wurst-Imperium/WurstClient.net#127]
When i add an alt that i know works, it just flashes red and deletes it.

**Comment by DevMaxC** [comment]
Using wurst 3.4

**Comment by ghost** [comment]
4 reasons:

1) You're offline.
2) You logged in (or attempted to login) too many times, and Mojang banned your IP for 24 hours.
3) You use a well-known Mojang-blocked proxy.
4) That account is not valid.
