### ISSUE TITLE
The baritone tutorial is out of date

### ISSUE THREAD

**Issue by feliscatusmeows** [Wurst-Imperium/WurstClient.net#170]
https://www.wurstclient.net/tutorials/wurst-7-baritone/ is out of date because the official baritone (https://github.com/cabaletta/baritone/releases) has been updated to work with fabric and fabaritone is no longer needed. The prefix for this is # again now.

**Comment by pythonmcpi** [comment]
I was also about to open an issue about this as well. I might make a pull request later if I manage to get baritone and wurst to work together.

**Comment by ZekePolarisBSH** [comment]
Does this mean this can't be used for it anymore?

**Comment by Alexander01998** [comment]
I've now removed the outdated tutorial from the website and made it redirect to this issue instead.

To reiterate for anyone coming from that redirect: Regular Baritone now supports Fabric, meaning you no longer need Fabritone. Instead, just add [Baritone itself](https://github.com/cabaletta/baritone/releases) to your mods folder. Make sure you download the `baritone-standalone-fabric-<version>.jar` file.

And just to be extra clear, no, this does not mean you can't use Baritone anymore. Quite the opposite, it's easier than ever!
