### ISSUE TITLE
zh_tw.json

### ISSUE THREAD

**Issue by ava852546** [Wurst-Imperium/WurstClient.net#172]
{
  "description.wurst.hack.anchoraura": "自動放置 (可選), 充能, 引爆重生錨並擊殺你附近的實體.",
  "description.wurst.hack.antiafk": "隨機走動,用於避免伺服器挂機檢測.\n需要至少有3x3的區域可以走動..",
  "description.wurst.hack.antiblind": "防止失明.\n與OptiFine不兼容.",
  "description.wurst.hack.anticactus": "保護你免受仙人掌傷害.",
  "description.wurst.hack.antiknockback": "保障你不會被其他生物或玩家推動以及遭到擊退.",
  "description.wurst.hack.antispam": "預防存在的重複洗頻,改為用計數器顯示.",
  "description.wurst.hack.antiwaterpush": "防止你被水流推動.",
  "description.wurst.hack.antiwobble": "關閉因反胃和傳送門引起的摇晃效果.",
  "description.wurst.hack.autoarmor": "自動管理你的盔甲.",
  "description.wurst.hack.autobuild": "自動建築東西.\n放一個方塊就開始建造.",
  "description.wurst.hack.autodrop": "自動丢棄你不想要的物品.",
  "description.wurst.hack.autoleave": "自動離開伺服器,當你的血量低於設定值.",
  "description.wurst.hack.autoeat": "在必要的時候自動進食.",
  "description.wurst.hack.autofarm": "自動收獲與種植植物.\n有效作物小麥,胡蘿蔔,馬鈴薯,甜菜根,南瓜, 西瓜, 仙人掌, 甘蔗, 海带,竹子, 地獄疙瘩, 和可可豆.",
  "description.wurst.hack.autofish": "自動釣魚同時使用你最好的魚竿，如果有更好的魚竿，將會自動使用,當你在釣魚的時候.",
  "description.wurst.hack.automine": "自動挖掘你眼前的方塊.",
  "description.wurst.hack.autopotion": "自動扔一瓶噴濺型,瞬間恢複,當你的生命值過低時候.",
  "description.wurst.hack.autoreconnect": "當你被伺服器踢出時候,自動重新鏈接.",
  "description.wurst.hack.autorespawn": "當你死亡的時候自動重生.",
  "description.wurst.hack.autosign": "立即在每個告示牌上寫下任何你想要的文字,當啟動的時候,你只需要很普通的在第一個告示牌上,寫你想要的文字,之後接下來所有告示牌都跟上一個一樣.",
  "description.wurst.hack.autosoup": "當你生命值低下的時候自動喝湯.\n\n§l注意:§r 這個功能是忽視'飢餓值',因為在某些游戲，喝湯直接補充生命,如果你正在玩的伺服器没有這個功能，請使用 AutoEat 功能而不是這個.",
  "description.wurst.hack.autosprint": "讓你自動跑步.",
  "description.wurst.hack.autosteal": "從你打開的箱子以及界伏盒,自動偷取所有物品.",
  "description.wurst.hack.autoswim": "自動切換泳姿狀態在水中.",
  "description.wurst.hack.autoswitch": "自動變換著手上的物品.\n\n§l進階提示:§r 利用這個功能與 BuildRandom 同時使用,在你的快捷欄上將會有不同顏色的羊毛以及,不同顏色的混凝土.",
  "description.wurst.hack.autosword": "自動使用快捷欄中最好的武器當你擊殺實體的時候.\n提示: 在使用 Killaura 功能時候，最好開啟.",
  "description.wurst.hack.autotool": "當你破壞方塊的時候,自動切換成適當的工具.(在你的物品快捷欄中選取)",
  "description.wurst.hack.autototem": "當你即將死亡的時候,自動將圖騰移動到副手上.",
  "description.wurst.hack.autowalk": "讓你自動走路.",
  "description.wurst.hack.basefinder": "尋找通過尋找人為建造的方塊以找到玩家的基地\n假如方塊被找到將會高亮以你所選的顏色.\n建議用於尋找幫派的基地.",
  "description.wurst.hack.blink": "在啟用時暫停所有動作更新.",
  "description.wurst.hack.boatfly": "允許你和你的船飛天",
  "description.wurst.hack.bonemealaura": "自動使用骨粉在指定的作物上.\n使用 檢查器 來指定作物.",
  "description.wurst.hack.bowaimbot": "自動瞄準,當你用弓或者弩時.",
  "description.wurst.hack.buildrandom": "在你的附近隨機放方塊.",
  "description.wurst.hack.bunnyhop": "讓你自動跳躍.",
  "description.wurst.hack.cameranoclip": "允許第三人稱忽視牆體直接穿過去.",
  "description.wurst.hack.cavefinder": "幫助你找到洞穴並將他們高亮以你所選的顏色.",
  "description.wurst.hack.chattranslator": "從聊天欄的信息利用Google翻譯成你所指定的語言.",
  "description.wurst.hack.chestesp": "高亮附近的箱子.",
  "description.wurst.hack.clickaura": "自動攻擊你附近有效的實體，當你點擊的時候.\n\n§c§l警告:§r 此功能通常來說比.Killaura 更加容易被發現且被檢測出來,這極力推薦使用 Killaura 或者 TriggerBot 作為替代.",
  "description.wurst.hack.clickgui": "類Windows樣點擊版GUI.",
  "description.wurst.hack.crashchest": "生成一個容易封禁玩家的箱子,如果他們複制大量的箱子在他們背包里面 §c§l警告:§r §c這個無法撤銷. 請小心使用!§r\n\n如果複制出來被放在箱子里, 無論誰打開箱子就會被踢出伺服器 (只要一個)..",
  "description.wurst.hack.creativeflight": "可以讓你跟創造模式的飛行一樣.\n\n§c§l警告:§r 如果你不使用 NoFall ,會導致受到掉落傷害.",
  "description.wurst.hack.criticals": "將你的攻擊全變為暴擊.",
  "description.wurst.hack.crystalaura": "自動放置 (可選) 並引爆終界水晶殺死你附近的實體.",
  "description.wurst.hack.derp": "讓你的頭瘋狂到處隨機轉動.\n只有其他玩家才看到.",
  "description.wurst.hack.dolphin": "讓你在水中自動浮起來.\n(就像海豚一樣)",
  "description.wurst.hack.excavator": "自動破壞所選區域内的所有方塊.",
  "description.wurst.hack.extraelytra": "讓你的鞘翅更加容易使用.",
  "description.wurst.hack.fancychat": "替換 ASCII 字符在發送消息時,變成更好的 unicode 字符. 可以用於繞過英文單詞字符限制在一些伺服器上.\n但對於那些禁用 unicode字符的伺服器不起作用.",
  "description.wurst.hack.fastbreak": "允許你更快的破壞方塊.\n提示: 可以和 Nuker 配合.",
  "description.wurst.hack.fastladder": "允許你爬梯的速度加快.",
  "description.wurst.hack.fastplace": "允許你一秒快速放置5個方塊.\n提示: 這個能增加 AutoBuild 功能 的速度.",
  "description.wurst.hack.feedaura": "自動喂食你附近的動物.",
  "description.wurst.hack.fightbot": "仿照機器人會自動跟隨並擊殺最近的實體.\n很適合刷怪區域.",
  "description.wurst.hack.fish": "關閉水下重力,所以你可以像魚一樣游泳.",
  "description.wurst.hack.flight": "允許你飛天.\n\n§c§l警告:§r 如果你不使用 NoFall ,會導致受到掉落傷害.",
  "description.wurst.hack.follow": "利用機器人方式會接近一個實體.\n非常惹惱人.\n\n使用 .follow 指令跟隨特定的實體.",
  "description.wurst.hack.forceop": "破解 AuthMe登入插件 密碼.\n一般用於獲得OP.（PS：只是撞資料庫跑密碼的軟體）",
  "description.wurst.hack.freecam": "允許在不移動你角色的情況下自由移動..",
  "description.wurst.hack.fullbright": "允許你在黑暗中看的一清二楚.",
  "description.wurst.hack.glide": "使你在下落時緩慢下降.\n\n§c§l警告:§r 如果你不使用 NoFall 則可能會摔落致死..",
  "description.wurst.hack.handnoclip": "允許你能透過牆壁触碰到特殊的方塊.",
  "description.wurst.hack.headroll": "讓你长期點頭.\n只有其他玩家能看到.",
  "description.wurst.hack.healthtags": "在玩家名字旁邊顯示血量.",
  "description.wurst.hack.highjump": "允許你跳的更高.\n\n§c§l警告:§r 如果你不使用 NoFall 則可能會摔落致死.",
  "description.wurst.hack.infinichat": "移除聊天欄的 256 字符限制.\n一般用於编辑NBT的指令.\n\n§6§l注意:§r 不推薦用於和别人聊天.大多數伺服器一般超過256字符就會被砍掉.",
  "description.wurst.hack.instantbunker": "建造一個小小的火柴盒. 需要57個方塊.",
  "description.wurst.hack.itemesp": "高亮附近的掉落物品.",
  "description.wurst.hack.itemgenerator": "生成隨機的物品並將他們丢在地上.\n§o僅限創造模式.§r",
  "description.wurst.hack.jesus": "允許你走在水面上.\n耶稣曾經用這個功能 約~2000 年前.",
  "description.wurst.hack.jetpack": "模仿你好像真的有飛行背包一樣飛行.\n\n§c§l警告:§r 如果你不使用 NoFall ,會導致受到掉落傷害..",
  "description.wurst.hack.kaboom": "像爆炸一樣破壞你附近的方塊.\n這個可能比 Nuker 功能破壞更快如果伺服器没有反作弊的話. 如果使用適合的工具和破壞脆弱的方塊的效果會更好.\n注意: 這並不是真正的爆炸.",
  "description.wurst.hack.killauralegit": "KillauraLegit 使得更难檢測.\n在正常的NoCheat+(NCP)伺服器上不需要!",
  "description.wurst.hack.killaura": "自動攻擊你附近的實體.",
  "description.wurst.hack.killpotion": "生成一個能殺死絕大多數生物的藥水,包括創造模式的玩家.但對那些不死的生物或者已死生物無效.\n\n需要在創造模式下.",
  "description.wurst.hack.liquids": "允許你在水中直接放方塊.",
  "description.wurst.hack.lsd": "產生吃了LSD一樣的效果.",
  "description.wurst.hack.masstpa": "給每個人發送tpa請求.\n如果有人接受了就停下來.",
  "description.wurst.hack.mileycyrus": "就是類似瘋狂按Shift潜行.",
  "description.wurst.hack.mobesp": "高亮附近的生物。",
  "description.wurst.hack.mobspawnesp": "高亮那些生物可以生成的區域.\n§e黄色§r 可以在夜間生成\n§c紅色§r - 可以在任意時候生成",
  "description.wurst.hack.multiaura": "比 Killaura 更高級,能同一時間攻擊多個實體.",
  "description.wurst.hack.nameprotect": "隱藏所有玩家的名字.",
  "description.wurst.hack.nametags": "改變名字顯示的大小使你可以經常可以看到他們. 同時也能讓你看到那些正在潜行的玩家名字.",
  "description.wurst.hack.navigator": "一個可搜索的GUI，可以隨著時間的推移了解您的偏好.",
  "description.wurst.hack.nobackground": "移除暗色背景像背包物品欄後面的暗色..",
  "description.wurst.hack.noclip": "允許你自由的穿過方塊.\n一個 (例.如. 沙子) 可以掉落的方塊掉在你的頭頂才能啟動.\n\n§c§l警告:§r 你將會受到傷害當你穿牆的時候!",
  "description.wurst.hack.nofall": "使你從高處摔下來無傷害.",
  "description.wurst.hack.nofireoverlay": "防止因身上有火而導致視野被覆蓋.\n\n§c§l警告:§r 這可能會導致你因不知道身上有火而燒傷致死.",
  "description.wurst.hack.nohurtcam": "關閉因受傷而產生視野摇晃效果.",
  "description.wurst.hack.nooverlay": "防止因在水中或岩漿產生視野遮擋.",
  "description.wurst.hack.nopumpkin": "防止因带南瓜頭而導致遮住視野.",
  "description.wurst.hack.noslowdown": "取消減速的效果像蜂蜜,靈魂沙,或者使用物品.",
  "description.wurst.hack.noweather": "允許改變你當地客戶端所在的時間,和月亮的階段(僅在本地生效,與伺服器無關).",
  "description.wurst.hack.noweb": "使你不會因為蜘蛛網而慢下來.",
  "description.wurst.hack.nuker": "自動挖掘你附近的方塊.",
  "description.wurst.hack.nukerlegit": "NukerLegit 能夠繞過所有的反作弊檢測.\n在正常的NoCheat+(NCP)伺服器上不需要!",
  "description.wurst.hack.openwateresp": "顯示你是否在一個'開放水域'的地方在區域内畫一個大的方塊用於計算檢測是否為開放水域.",
  "description.wurst.hack.overlay": "當你開採一個方塊時渲染 'Nuker功能' 動畫.",
  "description.wurst.hack.panic": "瞬間關閉所有的作弊功能.\n請小心使用!",
  "description.wurst.hack.parkour": "你會自動跳躍起來當到方塊的邊緣.\n適用於跑酷或跳和跑.",
  "description.wurst.hack.playeresp": "高亮透視附近的玩家.\n如果是你的好友的話會顯示藍色框框.",
  "description.wurst.hack.playerfinder": "在雷雨中尋找遠處的玩家.",
  "description.wurst.hack.portalgui": "允許你在傳送門内打開背包GUI.",
  "description.wurst.hack.potionsaver": "凍結所有的藥水效果當你站著不動時.",
  "description.wurst.hack.prophuntesp": "允許你知道哪些是人扮的方塊在躲猫猫中.\n用於 Mineplex 伺服器的 Prophunt(躲猫猫). 其他伺服器未必有效.",
  "description.wurst.hack.protect": "使用 AI模式 保護最近的實體，並保護它免受其他實體的傷害.\n使用指令 .protect 來保護指定的實體,而不是最近的一個.",
  "description.wurst.hack.radar": "生成一個雷達UI並顯示附近的實體.\n§c紅色§r - 玩家\n§6橘色§r - 怪物\n§a綠色§r - 動物\n§7灰色§r - 其他",
  "description.wurst.hack.rainbowui": "§c讓§a每§9一§c樣§a都 §9充§c滿§a五§9彩§c斑§a斕§9的§c樣§a子§9, §c包§a括§9你§c當§a前§9所§c在§aU§9I",
  "description.wurst.hack.reach": "允許你碰到/抵達更遠的距離.",
  "description.wurst.hack.remoteview": "允許你以另一個視角觀看世界.\n使用 .rv 指令來指定一個特殊的實體.",
  "description.wurst.hack.safewalk": "防止你從方塊邊緣掉出.",
  "description.wurst.hack.scaffoldwalk": "自動在你的腳下放置方塊.",
  "description.wurst.hack.search": "幫助你找到所需要的方塊並以彩虹色的方式高亮.",
  "description.wurst.hack.servercrasher": "生成一個物品可以崩掉1.15.x 的伺服器.\n§o僅限創造模式.§r",
  "description.wurst.hack.skinderp": "隨機切換你的皮膚.",
  "description.wurst.hack.sneak": "讓你自動保持潜行模式.",
  "description.wurst.hack.snowshoe": "可以讓你在細雪上行走.",
  "description.wurst.hack.speedhack": "允許你以大約 ~2.5x 或更快的速度跳躍或疾跑.\n\n§6§l警告:§r 只有低於反作弊版本 3.13.2.才會工作且繞過,如果你不知道伺服器反作弊是哪個版本..\n輸入 §l/ncp version§r 來查看反作弊版本.",
  "description.wurst.hack.speednuker": "一個比 Nuker 更快的版本,導致無法繞過反作弊.",
  "description.wurst.hack.spider": "像蜘蛛一樣能夠爬牆.",
  "description.wurst.hack.step": "允許你走上更高高度的格子方塊.",
  "description.wurst.hack.throw": "扔一個物品多次.可以用於丢雪球,雞蛋,生怪蛋,礦車,諸如此類.\n\n會生成大量的數量.這會產生大量的lag且可能會導致伺服器崩潰.",
  "description.wurst.hack.tillaura": "自動將泥土,草塊,诸如此類.轉化為农田.\n不要和Killaura搞混..",
  "description.wurst.hack.timer": "改變大部分東西的速度.",
  "description.wurst.hack.tired": "讓你看起來很像 Alexander回到 4月 2015年.\n僅限其他玩家可視.",
  "description.wurst.hack.toomanyhax": "隱藏那些你並不想要有的功能.\n讓你確保你不會不小心開啟錯誤的作弊功能導致被伺服器封禁.\n這個是給那些 \"只想作弊一點點的用戶\".\n\n使用指令 §6.toomanyhax§r 來選擇哪些功能需要被隱藏.\n輸入 §6.help toomanyhax§r 尋求更多.",
  "description.wurst.hack.tp-aura": "自動傳送到實體附近並自動攻擊他.",
  "description.wurst.hack.trajectories": "預測箭和投擲物品的飛行路徑.",
  "description.wurst.hack.treebot": "一個實驗性的機器人將會在樹木附近砍樹.\n目前僅限於砍小樹.",
  "description.wurst.hack.triggerbot": "自動攻擊你所看的實體.",
  "description.wurst.hack.trollpotion": "生成一個惹人惱怒的藥水效果.",
  "description.wurst.hack.truesight": "允許你看到隱形的實體.",
  "description.wurst.hack.tunneller": "自動挖一個隧道.\n\n§c§l警告:§r 盡管這個AI會自動避開岩漿和其他危險的地下,這裡没有守衛確保你不會死亡. 除非你不介意你的東西全部有一定機率會失去.",
  "description.wurst.hack.x-ray": "允許你通過牆看到礦物."
}

**Comment by Alexander01998** [comment]
Hi @andy3559167, thanks for the translation. However, this repository is for the WurstClient.net website rather than the Wurst Client itself. If you'd still like to change something about the Chinese translations, please open a pull request in [Wurst-Imperium/Wurst7](https://github.com/Wurst-Imperium/Wurst7/pulls) rather than an issue here.
