### ISSUE TITLE
What is IMC in the code of WurstClient

### ISSUE THREAD

**Issue by tanishisherewithhh** [Wurst-Imperium/WurstClient.net#173]
I am sorry if I should'nt be posting this here, but I can't wrap my head around `IMC` in your code:
Eg: `(IMC.getWorld())`

I cannot understand what IMC is and tried to look if it's something for initialization or within your GUI.
I am sorry if this is part of Minecraft or something. Since I am new to this.

**Comment by Alexander01998** [comment]
IMC is a mixin interface for Minecraft with some additional methods that wouldn't normally be accessible.

You can find a list of these mixin interfaces in the "net.wurstclient.mixinterface" package: https://github.com/Wurst-Imperium/Wurst7/tree/master/src/main/java/net/wurstclient/mixinterface

The actual implementations of these custom methods are in the mixins themselves: https://github.com/Wurst-Imperium/Wurst7/tree/master/src/main/java/net/wurstclient/mixin

Nowadays I typically use accessWideners to make Minecraft's private fields and methods accessible, but much of the codebase was written before accessWideners existed.

P.S.: This repo is for the website, not for the Wurst Client itself. Please use the Wurst7 repo next time.

**Comment by tanishisherewithhh** [comment]
Thanks. Sorry
