### ISSUE TITLE
make the wurst capes obey the new uuid instead of player names

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/WurstClient.net#2]

**Comment by Alexander01998** [comment]
Try asking the giveaway winners to send you their UUID over Twitter...

**Comment by pokeball99** [comment]
No need to do that,once they all havery given there ing,just use a program to find the uuid

**Comment by pokeball99** [comment]
Notice u having to update the usernames a lot,this would be an easy fix for that....
