### ISSUE TITLE
Main page bug (possibly intended?)

### ISSUE THREAD

**Issue by OMGchangeMYusername** [Wurst-Imperium/WurstClient.net#25]
![Image](http://puu.sh/j7eR7/be2f344f62.jpg)

I doubt it is intended,but sorry if it is.

**Comment by Alexander01998** [comment]
What screen size is that?

**Comment by OMGchangeMYusername** [comment]
Um.. idk what you mean but I have totally no problems with any other website.
![main page](https://cloud.githubusercontent.com/assets/10786571/9019004/3a615f7a-37ee-11e5-8789-814f81a2dc88.gif)

(I made that GIF with less frames, I also forgot the fifth "Wurst-Bots" picture but it's working fine)

**Comment by Alexander01998** [comment]
It works fine on a screen size of 1920x1080, for example.

**Comment by OMGchangeMYusername** [comment]
You mean the screen resolution of the whole monitor?
But why is it that every picture is working fine except this? even other sites are too fine..

**Comment by Alexander01998** [comment]
> You mean the screen resolution of the whole monitor?

Yes!

> But why is it that every picture is working fine except this? even other sites are too fine..

Because the layout of the site changes based on the screen size (a.k.a. responsive design). This is necessary to make it look good on desktops, laptops, tablets and smartphones. With big text and big images, responsive design can become very difficult.

**Comment by OMGchangeMYusername** [comment]
My screen resolution is 1680 x 1050, tried 1920x1080 but it didn't work. (of course 1920x1080 didn't fit in my screen but tried it anyway)

**Comment by Alexander01998** [comment]
Strange, that size is working fine for me.

![screenshot of wurst-client.tk](https://cloud.githubusercontent.com/assets/10100202/9043368/41308906-3a15-11e5-833b-10c9cfa6def4.png)

**Comment by Alexander01998** [comment]
What browser are you using?

**Comment by OMGchangeMYusername** [comment]
Firefox

**Comment by OMGchangeMYusername** [comment]
Well never mind if i'm the only one with this issue, I'll have to admit i have some problems in my PC but never faced problems with such things.
