### ISSUE TITLE
GitHub Format Still Used?

### ISSUE THREAD

**Issue by haykam** [Wurst-Imperium/WurstClient.net#26]
![Proof on website](http://i.gyazo.com/0ba70c66550f2ccaabef6d6e68ab5f67.png)
It says it still uses the GitHub format, and is hosted as a public source and you can fork it. However, it migrated away to a new one but still says this.

**Comment by Alexander01998** [comment]
> It says it still uses

It does.

> the GitHub format,

GitHub is not a format, it is a GitHub.

> and is hosted as a public source

It is.

> and you can fork it.

You can.

> However, it migrated away to a new one but still says this.

No, it didn't.

**Comment by haykam** [comment]
The wiki still says it is on GitHub.
