### ISSUE TITLE
search doesn't work

### ISSUE THREAD

**Issue by ghost** [Wurst-Imperium/WurstClient.net#30]

**Comment by OMGchangeMYusername** [comment]
![search](https://cloud.githubusercontent.com/assets/10786571/9024476/f1baf7e4-38d9-11e5-853f-7d76ae4f2001.gif)

**Comment by OMGchangeMYusername** [comment]
> You really need to get into the habit of adding a description to your Issues. -Alexander01998

![search](http://puu.sh/jm3WK/6f7a75f406.png)
Doesn't work for me either, there's no "go" or "search" button i can click here..
