### ISSUE TITLE
Why does it say mail is fake?

### ISSUE THREAD

**Issue by ghost** [Wurst-Imperium/WurstClient.net#48]

**Comment by Alexander01998** [comment]
It validates the email address by sending a request to the server asking if that address exists.
Some servers do not answer this request properly (for whatever reason), so that it looks like the address doesn't exist.

However, it works fine with popular email services like Gmail.

**Comment by ghost** [comment]
yahoo? @Alexander01998

**Comment by Alexander01998** [comment]
There are some problems with Yahoo: https://code.google.com/p/php-smtp-email-validation/issues/detail?id=5
