### ISSUE TITLE
who is getting the money from the new wurst shop?

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/WurstClient.net#50]
just wondering becuase of https://github.com/Wurst-Imperium/Wurst-Client/issues/421

**Comment by Alexander01998** [comment]
I am getting it.

As I said in Wurst-Imperium/Wurst-Client#1907, it is actually possible for me to make money online. It was just a little complicated and time consuming to set up.

At the time I wrote the comment in Wurst-Imperium/Wurst-Client#1907, I had little to no hope that I would get the required permissions and stuff before turning 18 and not needing them anymore. But now, about one month later, I did manage to get them.
