### ISSUE TITLE
How do I patch the MCP-decompiled sources?

### ISSUE THREAD

**Issue by beppe9000** [Wurst-Imperium/WurstClient.net#54]
@Alexander01998 @scriptinator I noticed your discussion about writing clearer tutorials (issue #15)...

I read the instructions on how to compile/debug Wurst. I have a problem with these steps:

> `4`. Create a local repository for your decompiled Minecraft source code.
> `5`. Go to your Wurst-Client clone and open the patch folder, there is a file called minecraft.patch. Apply that patch to your Minecraft repository.

This is my understanding of how a local repository is created:
`git init`
`git add .` (I am not sure about this... idk if `git add src` is better)
`git commit -m "mcp local repository"`

I executed the above commands while in the main MCP directory (the one with `decompile.sh`).

Next I run this:
`git apply --ignore-space-change --ignore-whitespace "..\Wurst-Client\patch\minecraft.patch"`

And it failed, with lots and lots of errors like this one:

`error: src/net/minecraft/client/gui/GuiTextField.java: No such file or directory`

Now, I think this is related to some path issue.

Can you enlighten me?

**Comment by Alexander01998** [comment]
That's the wrong directory. Your Minecraft source code needs to be in a folder called `src` and the repo needs to be in the parent folder of that.

MCP creates `src\minecraft` by default. A minimalist solution would be to rename that to `minecraft\src` and then creating the repo in `minecraft`.

**Comment by beppe9000** [comment]
Thanks, I fixed it with a folder junction :)

Is this output (mainly the patch does not apply" and non-existing `.gitignore`) acceptable?

> :\mcmod\mcp\src>git apply --ignore-space-change --ignore-whitespace minecraft.patch
> minecraft.patch:227: trailing whitespace.
> /tmp
> minecraft.patch:231: trailing whitespace.
> .project
> minecraft.patch:1748: trailing whitespace.
> package net.minecraft.block;
> minecraft.patch:1749: trailing whitespace.
> 
> minecraft.patch:1750: trailing whitespace.
> import java.util.Iterator;
> error: .gitignore: No such file or directory
> error: patch failed: src/net/minecraft/client/renderer/ThreadDownloadImageData.java:1
> error: src/net/minecraft/client/renderer/ThreadDownloadImageData.java: patch does not apply
> error: patch failed: src/net/minecraft/server/management/PlayerProfileCache.java:1
> error: src/net/minecraft/server/management/PlayerProfileCache.java: patch does not apply
> error: patch failed: src/net/minecraft/util/MessageDeserializer2.java:1
> error: src/net/minecraft/util/MessageDeserializer2.java: patch does not apply

**Comment by Alexander01998** [comment]
> Is this output (mainly the non-existing .gitignore) acceptable?

Maybe. See if you can start Wurst from Eclipse.

**Comment by beppe9000** [comment]
At first eclipse complained about missing jar files. I fixed that, but i were still unable to start, because of some security error with class `bcl`. So i deleted the 1.8 jar that contained it.

Then it crashed on start because of `no lwjgl in java.library.path`, so I added this to the arguments: `-Djava.library.path="d:\mcmods\mcp\jars\versions\1.8\1.8-natives"`.

I also added Slick.zip as a library (do i have to unpack it ?) to the mcp client project (the wurst project has no option to add libraries).

The current crashing trace is this:

<pre>
Exception in thread "Client thread" java.lang.ExceptionInInitializerError
    at net.minecraft.util.StatCollector.<clinit>(StatCollector.java:5)
    at net.minecraft.item.Item.getUnlocalizedNameInefficiently(Item.java:293)
    at net.minecraft.item.Item.getItemStackDisplayName(Item.java:416)
    at net.minecraft.item.ItemStack.getDisplayName(ItemStack.java:590)
    at net.minecraft.item.ItemStack.getChatComponent(ItemStack.java:1031)
    at net.minecraft.stats.StatList.func_151181_c(StatList.java:184)
    at net.minecraft.stats.StatList.func_151178_a(StatList.java:112)
    at net.minecraft.init.Bootstrap.register(Bootstrap.java:560)
    at net.minecraft.client.Minecraft.<init>(Minecraft.java:380)
    at net.minecraft.client.main.Main.main(Main.java:114)
    at Start.main(Start.java:11)
Caused by: java.lang.NullPointerException
    at java.io.Reader.<init>(Unknown Source)
    at java.io.InputStreamReader.<init>(Unknown Source)
    at org.apache.commons.io.IOUtils.readLines(IOUtils.java:986)
    at net.minecraft.util.StringTranslate.<init>(StringTranslate.java:42)
    at net.minecraft.util.StringTranslate.<clinit>(StringTranslate.java:28)
    ... 11 more
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
</pre>

Also, I'm not sure of what working directory (for eclipse) to select: the one inside the mcp folder or a freshly created one?

**Comment by Alexander01998** [comment]
The stack trace looks like the assets are missing, mainly the language files.

**Comment by beppe9000** [comment]
Looks like it was a patch problem, after all. I tried again and run `git apply --reject --whitespace=fix minecraft.patch` and it said it pached files. Now i have some `*.rej` files.

Then I opened Eclipse and set the working directory to the eclipse folder in mcp root and drag&dropped the contents of the `src` folder of the wurst repository on the existing `src` folder.
Then I fixed references to slick, authlib and realms.

This way **Wurst worked for me**.

I only encoutered a single problem: I get checkerboxed textures  instead of wurst-specific images.
Judging from the exceptions, there is a problem with the *.png path inside the jar file... but I won't care about a bunch of useless images.

**Comment by Ceiridge88** [comment]
I also have a problem with patching wurst.
I did everything in the tutorial, but it isn't working in the patch process.
I also have committed the vanilla minecraft, I have the vanilla source correctly.
But look what happens when I try to patch:

![](http://i.imgur.com/JECDdxI.png)

The errors in my workspace won't fix & when I commit the patch following commits: 

![](http://i.imgur.com/jbHEEKA.png)

I really want to help the wurst-community with new good code. (I've coded a client in MCP, with over 130 modules)
:pray: that you'll find an answer.

**Comment by Alexander01998** [comment]
Possible reasons:
- You used a different Minecraft version and/or a different MCP version
- You are using a non-Windows operating system and your computer broke the formatting (I warned you about that in the requirements section!).

**Comment by Ceiridge88** [comment]
@Alexander01998 I don't think that they are the reasons.
I used MCP 9.10 (1.8) and have Windows 8.1 installed.

**Comment by beppe9000** [comment]
did you try the second command i posted?
`git apply --reject --whitespace=fix minecraft.patch`

**Comment by Ceiridge88** [comment]
No, I'm going to try it right now

**Comment by Ceiridge88** [comment]
@beppe9000 Omg! It worked. Thank you :smile:

**Comment by beppe9000** [comment]
You are welcome.

**Comment by Ceiridge88** [comment]
Oh, and one question again: I want to edit something in the minecraft source. But I'm now allowed to upload the sources (because it's copyrighted to mojang etc.). 
So should I make a patch file for minecraft or should I say in comments what Alex should update/do?
@Alexander01998

**Comment by beppe9000** [comment]
You have to recreate the minecraft.path, then send a pr. However I stopped trying to contribute my mods, because of this dumb (in my opinion) way of managing contributions that involve changes to the MCP sources: for this reason I had proposed an easier to understand (human readable), compact (self-contained in the mod.java) way of expressing the accompanying MCP changes to mods that would make versioning and contributing more efficient and user friendly. Sadly, it was rejected by alexander, who censored this post for no obvious reason. I'm sure he will guide you step-by-step on the proper way of contributing mods.

**Comment by Ceiridge88** [comment]
Okay.

**Comment by Alexander01998** [comment]
> So should I make a patch file for minecraft or should I say in comments what Alex should update/do?

It's better to say that in the comments, as most people don't get how to recreate the patch correctly.
