### ISSUE TITLE
rss feed or similar to wurst feedback? 

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/WurstClient.net#58]
just for convenience sake if not for anything else

**Comment by Alexander01998** [comment]
What are you talking about?

**Comment by pokeball99** [comment]
well,something like the wurst new(pretty sure thats an rrs feed),also,how are you making the feedback app?don't see any code about it in this repo

**Comment by Alexander01998** [comment]
> well,something like the wurst new(pretty sure thats an rrs feed)

Yes, there is an RSS feed for the Wurst News. It's right here: https://www.wurst-client.tk/news/feed.xml

> also,how are you making the feedback app?don't see any code about it in this repo

The Wurst Feedback App is a separate, PHP based site on a different subdomain than the main Wurst website.

**Comment by pokeball99** [comment]
I'm not asking for the wurst news,I'm asking if you could make an RSS feed for the feedback app

**Comment by Alexander01998** [comment]
You should have suggested that in the Wurst Feedback App instead of this repo.

There's the feed: https://feedback.wurst-client.tk/new/feed.php
