### ISSUE TITLE
Download Count

### ISSUE THREAD

**Issue by ghost** [Wurst-Imperium/WurstClient.net#90]
The Download Count only counts number of downloads of the [Wurst-Client](https://github.com/Wurst-Imperium/Wurst-Client), Not [Wurst-Client-for-1.9.X](https://github.com/Wurst-Imperium/Wurst-Client-for-MC-1.9.X). If it counts both, probably DL count per second will be double.

**Comment by Alexander01998** [comment]
It is counting both repositories.

**Comment by ghost** [comment]
Are you sure?

> Counter for all Downloads of all Releases in one Repository

~ Alexander01998 [Gist](https://gist.github.com/Alexander01998/d5bda1558cfbc20a8ae3)

**Comment by Alexander01998** [comment]
I changed the code after I added the new repository.
